development:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_development
  pool: 5
<<<<<<< HEAD
  username: ethandeveloper
=======
  username: brendan
>>>>>>> 1eb1e8ec60c67e72fc080f354cb21dfed70cb554
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_test
  pool: 5
<<<<<<< HEAD
  username: ethandeveloper
=======
  username: brendan
>>>>>>> 1eb1e8ec60c67e72fc080f354cb21dfed70cb554
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_production
  pool: 5
<<<<<<< HEAD
  username: ethandeveloper
=======
  username: brendan
>>>>>>> 1eb1e8ec60c67e72fc080f354cb21dfed70cb554
  password:
