development:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_production
  pool: 5
  username: postgres
  password:
