development:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_development
  pool: 5
<<<<<<< HEAD
  username: ethandeveloper
=======
  username: brendan
>>>>>>> 040a015df6a97b85358454c11af5eb95b8cf261c
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_test
  pool: 5
<<<<<<< HEAD
  username: ethandeveloper
=======
  username: brendan
>>>>>>> 040a015df6a97b85358454c11af5eb95b8cf261c
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nasa_missions_production
  pool: 5
<<<<<<< HEAD
  username: ethandeveloper
=======
  username: brendan
>>>>>>> 040a015df6a97b85358454c11af5eb95b8cf261c
  password:
